c :
	rm *.out ashwin.txt trystat trylseek tryunlink tryreaddir tailm

stat:
	gcc trystat.c -o trystat

lseeking :
	gcc lstattry.c  -o trylseek
delete :
	gcc unlinktry.c -o tryunlink
readdir:
	gcc readdirtry.c -o tryreaddir
tail :
	gcc tailmock.c -o tailm
